version: "2.0"
services:
  springboot:
    build: .
    container_name: apontador
    ports:
      - 8182:8080
    depends_on:
      - mongo
    networks:
      - app-apontador
  mongo:
    image: mongo
    container_name: apontador-mongodb
    ports:
      - 27018:27017
    environment:
      MONGODB_APPLICATION_DATABASE: db_apontador
    networks:
      - app-apontador
    command: mongod 
networks:
  app-apontador:
    driver: bridge